# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_binary_packages:
  - dplyr

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
